### ISSUE TITLE
Refine outputs

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-websphere-liberty-operator#14]
### Description

Could of suggestions:
- Surface outputs as discrete values rather than a map. 
- Add https:// to the websphere_liberty_operator_sampleapp_url output.

Current output:

``` 
{
   "websphere_liberty_operator_sampleapp_url": "websphereliberty-app-sample-samplelibertyapp.allpublic-workload-cluste-86a93ec9a58da2fad5fd584803ad1b3d-0000.eu-es.containers.appdomain.cloud",
  "ws_liberty_operator_namespace": "openshift-operators",
  "ws_liberty_operator_target_namespace": null
}
```

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vbontempi** [comment]
Addressing with https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/11

**Comment by vbontempi** [comment]
completed with version 1.0.1
